
version: 2

models:
    - name: raw_table
      description: "the very raw table of bq"
      columns:
          - name: int64_field_0
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: game_date
          - name: bookmaker
          - name: odd_home
          - name: odd_even
          - name: odd_exte
          - name: link

    - name: stag_1
      description: "testing stuff"
      columns:
          - name: int64_field_0
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: game_date
          - name: bookmaker
          - name: odd_home
          - name: odd_even
          - name: odd_exte
          - name: link
